### ISSUE TITLE
Custom "max allow depletion" default value

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#38] opened 2015-04-09 14:51 UTC
In the custom "max allow depletion" field the default value "100% Inet" should appear, in order to provide guidance to the users.

**Comment by kickapoo** [comment] 2015-04-10 13:09
Duplicate of #35

**Comment by kickapoo** [comment] 2015-04-10 13:09
Duplicate of #35

**Closed by kickapoo** 2015-04-10 13:09 UTC
Labels: duplicate
