### ISSUE TITLE
Custom Wilting Point in "update_agrifield"

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#33] opened 2015-04-09 14:46 UTC
Along with the other custom parameters, the user should have the ability to insert custom Wilting Point in "update_agrifield" page.
The default value (taken from the rasters) should appear in order to provide guidance.

**Comment by kickapoo** [comment] 2015-04-10 13:28
Duplicate of #32

**Closed by kickapoo** 2015-04-10 13:28 UTC
Labels: duplicate
